export const env = {
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID:
    process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID || "",
  NEXT_PUBLIC_SOMNIA_FACTORY_ADDRESS:
    process.env.NEXT_PUBLIC_SOMNIA_FACTORY_ADDRESS || "",
  NEXT_PUBLIC_NFT_PROFILE_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_NFT_PROFILE_CONTRACT_ADDRESS || "",
  NEXT_PUBLIC_AVATAR_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_AVATAR_CONTRACT_ADDRESS || "",
  NEXT_PUBLIC_BE_GRAPHQL_URL: process.env.NEXT_PUBLIC_BE_GRAPHQL_URL || "",
};
