const randomNames = [
  "Lainey Villanueva",
  "Huxley Medrano",
  "Halle Ramsey",
  "Luciano Pierce",
  "Arabella Melendez",
  "Nikolas Garza",
  "River Fields",
  "Clayton Pacheco",
  "Paris Bridges",
  "Mohammed Acevedo",
  "Ashlynn Hobbs",
  "Brendan Preston",
  "Indie Roach",
  "Caspian Shah",
  "Angelica Hester",
  "Rene Richmond",
  "Whitney Petersen",
  "Samson Gordon",
  "Taylor Prince",
  "Aron Allison",
  "Chelsea Dennis",
  "Emanuel Lugo",
  "Kaylie Rowe",
  "Kamden Hunter",
  "Khloe Nichols",
  "Atlas Cantu",
  "Galilea Johnson",
  "Noah Merritt",
  "Kaisley Carr",
  "Kash Griffith",
  "Alicia Luna",
  "Erick Hensley",
  "Malaya Vincent",
  "Aarav Weber",
  "Alayah Miles",
  "Jared Sullivan",
  "Melanie McFarland",
  "Dane Bell",
  "Melody King",
  "Julian McPherson",
  "Emmaline Woodard",
  "Westley Bradshaw",
  "Berkley Frye",
  "Franco Pacheco",
  "Paris Corona",
  "Darian Hurst",
  "Adalee Terry",
  "Armani Becker",
  "Laura Price",
  "Brooks Salinas",
];

export const getRandomName = () => {
  return randomNames[Math.floor(Math.random() * randomNames.length)];
};
